// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0FXW4Og3KuCjDTthXSK_uyr8inVAc-s',
    appId: '1:597908010367:web:6d459845e7f8b9fcbad64a',
    messagingSenderId: '597908010367',
    projectId: 'mahasiswa-698d5',
    authDomain: 'mahasiswa-698d5.firebaseapp.com',
    storageBucket: 'mahasiswa-698d5.firebasestorage.app',
    measurementId: 'G-LPM0RZKMHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnSsD2wgGMJXOoyBSwQw3FLRjHkOHoFVw',
    appId: '1:597908010367:android:6b1b096d1bf6d01ebad64a',
    messagingSenderId: '597908010367',
    projectId: 'mahasiswa-698d5',
    storageBucket: 'mahasiswa-698d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUd-AJqDy474_7Nx7QTVIwwrA-WghfZKw',
    appId: '1:597908010367:ios:e3c13afe2e15a459bad64a',
    messagingSenderId: '597908010367',
    projectId: 'mahasiswa-698d5',
    storageBucket: 'mahasiswa-698d5.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUd-AJqDy474_7Nx7QTVIwwrA-WghfZKw',
    appId: '1:597908010367:ios:e3c13afe2e15a459bad64a',
    messagingSenderId: '597908010367',
    projectId: 'mahasiswa-698d5',
    storageBucket: 'mahasiswa-698d5.firebasestorage.app',
    iosBundleId: 'com.example.mahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF0FXW4Og3KuCjDTthXSK_uyr8inVAc-s',
    appId: '1:597908010367:web:0e6c9037f4e902b3bad64a',
    messagingSenderId: '597908010367',
    projectId: 'mahasiswa-698d5',
    authDomain: 'mahasiswa-698d5.firebaseapp.com',
    storageBucket: 'mahasiswa-698d5.firebasestorage.app',
    measurementId: 'G-1VJ8MRKW1F',
  );
}
